### ISSUE TITLE
Generated files should not be checked in

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator-py#16]
Generated files should not be checked in. If local schema is not found, it should fetch from tatorapp.com

**Comment by jrtcppv** [comment]
Build from main repo:
* Generate schema.yaml from the manage.py command
* Invoke setup.py from Makefile to generate a wheel
* setup.py runs openapi-generator via docker to generate code
* Main repo copies the wheel into container images for use in tator

Build from standalone tator-py:
* setup.py is invoked as normal with `python3 setup.py install`
* setup.py downloads schema.yaml from tatorapp.com (triggered if local schema.yaml not found)
* setup.py runs openapi-generator via docker to generate code
* setup.py continues normal install/build
