### ISSUE TITLE
Error checking breaks GCS uploads

### ISSUE THREAD

**Issue by BGWoodward** [cvisionai/tator-py#59]
Currently GCS uploads are broken, because it uses a resumable session path, which doesn't utilize the `ETag` paradigm. This used to be transparently handled through a `get` on the headers, and stuffing in the chunk number for that parameter if it wasn't returned (as would always be the case for GCS). However, commit **b8753266e0d6f4252461ea7600eb4e1001db4c9e** enforced a stricter check for that header, and broke the GCS path. 

Recommend fixing the check to not occur if it is a GCS upload, or make the robustness check more explicit for each upload path

Relevant code is in tator/util/_upload_file.py - line 82

**Comment by henxing** [comment]
Addressed in [89c541f4d46fc51a5e8f46ff39c5dd87675d4d8f](https://github.com/cvisionai/tator-py/commit/89c541f4d46fc51a5e8f46ff39c5dd87675d4d8f).
