### ISSUE TITLE
Transcode module's --cleanup function deletes input media

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator-py#60]
When using 'python -m tarot.transcode VIDEO.MP4 --work_dir TRANSCODE_DIR --cleanup' I expected only the files under TRANSCIDE_DIR to be deleted. Instead, VIDEO.MP4 also gets deleted. 

This caused me to lose the full resolution videos for my project. 

If this is not the intended behavior, then this is a big and should be fixed. If this IS the intended behavior, then the '--help' text for the '--cleanup' flag should be updated. The current help text, "Deletes working files after each file is transcoded and uploaded" doesn't make this clear

**Comment by jrtcppv** [comment]
That is definitely an oversight and we will prioritize this for a fix in an upcoming release.

**Comment by jrtcppv** [comment]
I am putting the fix for this issue into the release candidate branch for Tator `0.2.23`, with official release scheduled for early next week. In the meantime, I just updated the wheel on pypi (version `0.10.29`) with this fix. From `0.2.23` on the pypi package version will match the current stable tator release version. Really sorry about this issue.

**Comment by sbatchelder** [comment]
Hi Jon,

It was mostly surprising/a little scary. I don't think any data was lost forever. We either have backups or the still images the videos were derived from saved elsewhere.

Glad you got a fix in quick.

-Sidney

________________________________
From: Jonathan Takahashi ***@***.***>
Sent: Wednesday, February 22, 2023 7:14 PM
To: cvisionai/tator-py ***@***.***>
Cc: Sidney Batchelder (she/her) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [cvisionai/tator-py] Transcode module's --cleanup function deletes input media (Issue #60)

This email originated outside of WHOI. Please use caution if clicking on links or opening attachments.

I am putting the fix for this issue into the release candidate branch for Tator 0.2.23, with official release scheduled for early next week. In the meantime, I just updated the wheel on pypi (version 0.10.29) with this fix. From 0.2.23 on the pypi package version will match the current stable tator release version. Really sorry about this issue.
