### ISSUE TITLE
api.get_localization_list fails?

### ISSUE THREAD

**Issue by sbatchelder** [cvisionai/tator-py#62]
Some `int` input filter parameters for `api.get_localization_list()` fail unexpectedly. 
`media_id` and `version` for instance only work when wrapped with a `[ ]` list. Others like `frame` simply fail. Curiously `type` seems to work fine (and I didn't test 'section'). 

The error is almost always with same (see trace below) with the exception of trying to provide `frame` as a list. 

```
# WORKS
api.get_locatization_list(project=1)
api.get_locatization_list(project=1, media_id=[335])
api.get_locatization_list(project=1, version=[11])
api.get_localization_list(project=1, type=1)

# FAILS
api.get_locatization_list(project=1, media_id=335)
api.get_locatization_list(project=1, media_id=[335], frame=[34021]) 
api.get_locatization_list(project=1, version=11)
```

Typical traceback on failure
```
  File ".../tator/lib/python3.11/site-packages/tator/openapi/tator_openapi/api/tator_api.py", line 16407, in get_localization_list
    return self.get_localization_list_with_http_info(project, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../tator/lib/python3.11/site-packages/tator/openapi/tator_openapi/api/tator_api.py", line 16627, in get_localization_list_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../tator/lib/python3.11/site-packages/tator/openapi/tator_openapi/api_client.py", line 365, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../tator/lib/python3.11/site-packages/tator/openapi/tator_openapi/api_client.py", line 155, in __call_api
    query_params = self.parameters_to_tuples(query_params,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../tator/lib/python3.11/site-packages/tator/openapi/tator_openapi/api_client.py", line 469, in parameters_to_tuples
    (k, delimiter.join(str(value) for value in v)))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable

```

tator-py version: 1.0.0

**Comment by jrtcppv** [comment]
Hi @sbatchelder, I looked at the schemas for Tator `0.2.23` and Tator `1.0.0` and it looks like in both `media_id` is a list of integers, and `frame` is an integer (not a list). Given this, I would expect the call:
`api.get_locatization_list(project=1, media_id=[335], frame=34021)`
to work fine. I suspected an issue potentially around client/server version mismatch, but I tried this same call on the following:

* tator-py `0.2.23` making calls to tator `0.2.23`
* tator-py `0.2.23` making calls to tator `1.0.0`
* tator-py `1.0.0` making calls to tator `0.2.23`
* tator-py `1.0.0` making calls to tator `1.0.0`

And in all cases I was unable to reproduce the issue. Can you give me the error message that results from using a list for `media_id` and an integer for `frame`? I'm wondering if it's a server side error unrelated to the client.

Also, wanted to point out that the alignment between `tator-py` and `tator` version is a recent thing, versions are aligned in `0.2.23` and later.

**Comment by sbatchelder** [comment]
Ah, I misread the documentation. I read those inputs as int _or_ [int**].
As for my error, I apparently can't reproduce it either. The frame search parameter is working fine. I must have gotten turned around wrt `[int**]`

I did run into a different difficulty with using `attribute="Verified::True,Class::salpa_aspera"`. 
Is this a schema mistake on my part as well, or a bug?
```
>> kwargs = {'project':1, 'attribute':'Class::salpa_aspera', 'media_id':[335], 'version':[11]}
>> locs = api.get_localization_list(**kwargs)

Server Response:
  message: "not enough values to unpack (expected 2, got 1)"

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/tator_online/main/rest/_base_views.py", line 47, in get
    response_data = self._get(params)
  File "/tator_online/main/rest/localization.py", line 65, in _get
    qs = get_annotation_queryset(self.kwargs['project'], params, 'localization')
  File "/tator_online/main/rest/_annotation_query.py", line 227, in get_annotation_queryset
    use_es, filter_ops = _use_es(project, params)
  File "/tator_online/main/rest/_annotation_query.py", line 220, in _use_es
    use_es_for_attributes, filter_ops = get_attribute_filter_ops(project, params)
  File "/tator_online/main/rest/_attribute_query.py", line 276, in get_attribute_filter_ops
    key, value, dtype = _convert_attribute_filter_value(kv, mappings, op)
  File "/tator_online/main/rest/_attribute_query.py", line 245, in _convert_attribute_filter_value
    key, value = kv
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by jrtcppv** [comment]
Okay glad to hear that is resolved. According to the schema for `0.2.23` and `1.0.0`, they both have the `attribute` parameter as a list of strings, so I believe you would want to modify your query as:

```
>> kwargs = {'project':1, 'attribute':['Class::salpa_aspera'], 'media_id':[335], 'version':[11]}
>> locs = api.get_localization_list(**kwargs)
```
Let me know if that works. I took a look at the tator-py documentation for that parameter and it is a bit confusing, so we have an action to clarify that.

**Comment by sbatchelder** [comment]
Yup, I was just reading the schema wrong again. 
My bad everyone!
